// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCk2Of-6Q9-6-8me6iWm9qJUFUEFNTjek',
    appId: '1:710577098803:web:d9117addd873c9abd05346',
    messagingSenderId: '710577098803',
    projectId: 'room-70d91',
    authDomain: 'room-70d91.firebaseapp.com',
    storageBucket: 'room-70d91.appspot.com',
    measurementId: 'G-EKNZXF7Y1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFPdg7XkMzvjV2vPMwS0Nz_2iHeSPhWIA',
    appId: '1:710577098803:android:914027f3fb0d64ead05346',
    messagingSenderId: '710577098803',
    projectId: 'room-70d91',
    storageBucket: 'room-70d91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtuA7lU0fjZnNW53CI22LSXqvcdana6k',
    appId: '1:710577098803:ios:8dd2da26d0bd0927d05346',
    messagingSenderId: '710577098803',
    projectId: 'room-70d91',
    storageBucket: 'room-70d91.appspot.com',
    iosClientId: '710577098803-se78fn6uoj3uke1trg5h4cel0i881v56.apps.googleusercontent.com',
    iosBundleId: 'com.room.tmt',
  );
}
